# NSSF (Network Slice Selection Function): Seleciona as instâncias de fatias de rede (Network Slices) que servirão ao dispositivo.
logger:
  level: info

nssf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777

    client:
      nrf:
        - uri: http://nrf:7777

      nsi:
        - uri: http://nrf:7777
          s_nssai:
            sst: 1
